// Generated by gencpp from file primeiro_proj/situation.msg
// DO NOT EDIT!


#ifndef PRIMEIRO_PROJ_MESSAGE_SITUATION_H
#define PRIMEIRO_PROJ_MESSAGE_SITUATION_H

#include <ros/service_traits.h>


#include <primeiro_proj/situationRequest.h>
#include <primeiro_proj/situationResponse.h>


namespace primeiro_proj
{

struct situation
{

typedef situationRequest Request;
typedef situationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct situation
} // namespace primeiro_proj


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::primeiro_proj::situation > {
  static const char* value()
  {
    return "f737e5fcbaaa86f9d9437904e7db66b6";
  }

  static const char* value(const ::primeiro_proj::situation&) { return value(); }
};

template<>
struct DataType< ::primeiro_proj::situation > {
  static const char* value()
  {
    return "primeiro_proj/situation";
  }

  static const char* value(const ::primeiro_proj::situation&) { return value(); }
};


// service_traits::MD5Sum< ::primeiro_proj::situationRequest> should match
// service_traits::MD5Sum< ::primeiro_proj::situation >
template<>
struct MD5Sum< ::primeiro_proj::situationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::primeiro_proj::situation >::value();
  }
  static const char* value(const ::primeiro_proj::situationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::primeiro_proj::situationRequest> should match
// service_traits::DataType< ::primeiro_proj::situation >
template<>
struct DataType< ::primeiro_proj::situationRequest>
{
  static const char* value()
  {
    return DataType< ::primeiro_proj::situation >::value();
  }
  static const char* value(const ::primeiro_proj::situationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::primeiro_proj::situationResponse> should match
// service_traits::MD5Sum< ::primeiro_proj::situation >
template<>
struct MD5Sum< ::primeiro_proj::situationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::primeiro_proj::situation >::value();
  }
  static const char* value(const ::primeiro_proj::situationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::primeiro_proj::situationResponse> should match
// service_traits::DataType< ::primeiro_proj::situation >
template<>
struct DataType< ::primeiro_proj::situationResponse>
{
  static const char* value()
  {
    return DataType< ::primeiro_proj::situation >::value();
  }
  static const char* value(const ::primeiro_proj::situationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRIMEIRO_PROJ_MESSAGE_SITUATION_H
