// Generated by gencpp from file primeiro_proj/situationRequest.msg
// DO NOT EDIT!


#ifndef PRIMEIRO_PROJ_MESSAGE_SITUATIONREQUEST_H
#define PRIMEIRO_PROJ_MESSAGE_SITUATIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace primeiro_proj
{
template <class ContainerAllocator>
struct situationRequest_
{
  typedef situationRequest_<ContainerAllocator> Type;

  situationRequest_()
    {
    }
  situationRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::primeiro_proj::situationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::primeiro_proj::situationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct situationRequest_

typedef ::primeiro_proj::situationRequest_<std::allocator<void> > situationRequest;

typedef boost::shared_ptr< ::primeiro_proj::situationRequest > situationRequestPtr;
typedef boost::shared_ptr< ::primeiro_proj::situationRequest const> situationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::primeiro_proj::situationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::primeiro_proj::situationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace primeiro_proj

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::primeiro_proj::situationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::primeiro_proj::situationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::primeiro_proj::situationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::primeiro_proj::situationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::primeiro_proj::situationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::primeiro_proj::situationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::primeiro_proj::situationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::primeiro_proj::situationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::primeiro_proj::situationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "primeiro_proj/situationRequest";
  }

  static const char* value(const ::primeiro_proj::situationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::primeiro_proj::situationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::primeiro_proj::situationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::primeiro_proj::situationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct situationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::primeiro_proj::situationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::primeiro_proj::situationRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PRIMEIRO_PROJ_MESSAGE_SITUATIONREQUEST_H
